kind: pipeline
type: docker
name: default

steps:
- name: build_app
  image: plugins/docker
  settings:
    dockerfile: ./app/Dockerfile
    repo: app
    tags: latest
  commands:
    - docker compose -f dev.yml build
    - docker compose -f dev.yml up

- name: build_playwright_tests
  image: plugins/docker
  settings:
    dockerfile: ./test/Dockerfile
    repo: playwright-tests
    tags: latest

- name: run_tests
  image: playwright-tests:latest
  commands:
    - npx playwright test

services:
- name: db
  image: mysql:latest
  environment:
    MYSQL_ROOT_PASSWORD: SprintRunners
    MYSQL_DATABASE: mydb
