kind: pipeline
type: docker
name: default

services:
  app:
    image: docker:dind
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app/src:/app/src
      - ./app/public:/app/public
      - name: dockersock
        path: /var/run
    ports:
      - "3001:3000"
    networks:
      - my_network

  playwright-tests:
    image: docker:dind
    build:
      context: .
      dockerfile: ./test/Dockerfile
    volumes:
      - ./test:/tests
      - name: dockersock
        path: /var/run
    depends_on:
      - app
    networks:
      - my_network
    working_dir: /test

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=SprintRunners
      - MYSQL_DATABASE=mydb
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my_network

volumes:
  db_data:
  dockersock:
    host:
      path: /var/run

networks:
  my_network:
    external: true
