kind: pipeline
type: docker
name: default

steps:
- name: build_app
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run
  environment:
    DOCKER_USERNAME:
      from_secret: yatharthmathur711 #fill here your docker username
    DOCKER_REPO:
      from_secret: team-3-capstone-sprint-runners
    DOCKER_TAG:
      from_secret: latest
  commands:
  - docker build -f ./app/Dockerfile -t $DOCKER_USERNAME/$DOCKER_REPO:$DOCKER_TAG ./app

- name: build_playwright_tests
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run
  environment:
    DOCKER_USERNAME:
      from_secret: yatharthmathur711 #fill here your docker username
    DOCKER_REPO:
      from_secret: team-3-capstone-sprint-runners
    DOCKER_TAG:
      from_secret: latest
  commands:
  - docker build -f ./test/Dockerfile -t $DOCKER_USERNAME/$DOCKER_REPO:playwright-tests .

- name: test
  image: $DOCKER_USERNAME/$DOCKER_REPO:playwright-tests
  commands:
  - npm install
  - npm run test

services:
- name: app
  image: $DOCKER_USERNAME/$DOCKER_REPO:$DOCKER_TAG
  environment:
    ENV_VARIABLE:
      from_secret: ENV_VARIABLE
    NEXT_PUBLIC_ENV_VARIABLE:
      from_secret: NEXT_PUBLIC_ENV_VARIABLE
  ports:
  - 3001
  volumes:
  - name: app_src
    path: /app/src
  - name: app_public
    path: /app/public

volumes:
- name: dockersock
  host:
    path: /var/run
- name: app_src
  temp: {}
- name: app_public
  temp: {}
