kind: pipeline
type: docker
name: default

steps:
- name: build_app  
  image: node:latest
  volumes:
    - name: dockersock
      path: /var/run
  commands:
    - docker build -f ./app/Dockerfile -t app:latest ./app

- name: build_playwright_tests
  image: node:latest
  volumes:
    - name: dockersock
      path: /var/run
  commands:
    - docker build -f ./test/Dockerfile -t playwright-tests:latest .

- name: run_tests
  image: playwright-tests:latest
  commands:
    - npx playwright test

services:
- name: db
  image: mysql:latest
  environment:
    MYSQL_ROOT_PASSWORD: SprintRunners
    MYSQL_DATABASE: mydb
volumes:
- name: dockersock
  host:
    path: /var/run


