version: "3"

services:
  app:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      ENV_VARIABLE: ${ENV_VARIABLE}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    env_file:
      - .env
    volumes:
      - ./app/src:/app/src
      - ./app/public:/app/public
    restart: always
    ports:
      - 3001:3000
    networks:
      - my_network
  
  playwright-tests:
    container_name: playwright-tests
    build:
      context: .
      dockerfile: ./test/Dockerfile # Ensure you have a Dockerfile for Playwright setup
    volumes:
      - ./test:/test # Assuming your tests are in the ./test directory
    depends_on:
      - app
    networks:
      - my_network
    working_dir: /test
    

networks:
  my_network:
    external: true