version: "3.8"

services:
  app:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      ENV_VARIABLE: ${ENV_VARIABLE}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    env_file:
      - .env
    volumes:
      - ./app/src:/app/src
      - ./app/public:/app/public
    restart: always
    ports:
      - "3000:3000"
    networks:
      - my_network
  
  playwright:
    build:
      context: ./app/server-test
      dockerfile: Dockerfile.playwright # Ensure you have a Dockerfile for Playwright setup
    volumes:
      - ./app/server-test:/app/server-test # Mount the test directory to /app/tests in the container
    depends_on:
      - db
      - app
    networks:
      - my_network
    working_dir: /app
    # command: /bin/sh -c "npm run dev && npx playwright test"
    
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=SprintRunners
      - MYSQL_DATABASE=mydb
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my_network

  jest:
    build:
      context: ./app/server-test
      dockerfile: Dockerfile.jest # Ensure you have a Dockerfile for Jest setup
    volumes:
      - ./app/server-test:/app # Mount the test directory to /test in the container
    depends_on:
      - app
      - db
    networks:
      - my_network
    working_dir: /app
    command: npm run test:jest
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=SprintRunners
      - MYSQL_DATABASE=mydb
    

# Define a volume, which is a directory that is stored outside of the container's filesystem
volumes:
  db_data:
  # Add more containers below OUR DB BUILD***


# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  my_network:
    external: true