version: '3.9'

services:
  app:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      ENV_VARIABLE: ${ENV_VARIABLE}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    env_file:
      - .env
    volumes:
      - ./app/src:/app/src
      - ./app/public:/app/public
      - ./app/server-test:/app/server-test
    restart: always
    ports:
      - "3001:3000"
    networks:
      - my_network

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=SprintRunners
      - MYSQL_DATABASE=mydb
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my_network
    ports:
      - "3307:3306"

  # playwright-tests:
  #   container_name: playwright-tests
  #   build:
  #     context: .
  #     dockerfile: ./test/Dockerfile # Ensure you have a Dockerfile for Playwright setup
  #   volumes:
  #     - ./test:/tests # Assuming your tests are in the ./test directory
  #   depends_on:
  #     - app
  #   networks:
  #     - my_network
  #   working_dir: /test

volumes:
  db_data:
  # Add more containers below OUR DB BUILD***


# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  my_network:
