version: "3"

services:
  app:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile

    # Set environment variables directly in the docker-compose file
    environment:
      ENV_VARIABLE: ${ENV_VARIABLE}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}

    # Set environment variables based on the .env file
    env_file:
      - .env
    volumes:
      - ./app/src:/app/src
      - ./app/public:/app/public
    restart: always
    ports:
      - "3001:3000"
    networks:
      - my_network

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=SprintRunners
      - MYSQL_DATABASE=mydb
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my_network

volumes:
  db_data:
  # Add more containers below OUR DB BUILD***


# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  my_network:
    external: true
