FROM node:latest

WORKDIR /app

# Update package list and install system dependencies for Playwright
RUN apt-get update && apt-get install -y
RUN npm install -g npm@latest

# Copy only package.json initially to leverage Docker cache
COPY ../package*.json ./

# Install Playwright as a local dependency
RUN npm install playwright --save-dev --save-exact

# Now copy the rest of the test scripts
# COPY ./app/test ./app/test

# Install necessary browsers
RUN npx playwright install --with-deps chromium

# Run tests (adjust command as needed)
CMD ["npx", "playwright", "test"]
